import os
from app.schemas.ai_report import AIReportRequest, AIReportResponse

BEHAVIOURS = [
    "Eye Contact",
    "Joint Attention",
    "Response to Name",
    "Gestures",
    "Turn Taking",
    "Initiation",
    "Following Instructions",
    "Requesting",
    "Social Greeting",
    "Communication Intent",
]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


def build_prompt(data: AIReportRequest) -> str:
    """
    Builds the prompt sent to Gemini. Explicitly instructs the model
    to draft only, avoid diagnosis, and use observational language.
    """
    behaviour_lines = "\n".join(
        f"- {b.behaviour_name}: score {b.score}/5, notes: {b.notes or 'N/A'}"
        for b in data.behaviours
    )

    prompt = f"""
You are assisting a licensed Speech-Language Pathologist (SLP) by drafting
a communication assessment summary. This is a DRAFT ONLY. The SLP will
review, edit, and approve it before it is used with any patient or family.

STRICT RULES:
- Do NOT provide a diagnosis or diagnostic label of any kind.
- Do NOT suggest a medical or psychological condition.
- Use observational, descriptive language only (e.g. "the child showed limited eye contact during the session" instead of clinical conclusions).
- Clearly state this is a draft requiring clinician review.

Patient Name: {data.patient_name}
Age: {data.age}
Assessment Date: {data.assessment_date}

Behaviour Observations:
{behaviour_lines}

Write a structured draft report with the following sections:
1. Summary of Observations
2. Strengths Noted
3. Areas Needing Support
4. Suggested Next Steps for the SLP to Consider

Keep the tone professional, neutral, and non-diagnostic.
"""
    return prompt.strip()


def generate_mock_report(data: AIReportRequest) -> str:
    """
    Returns a placeholder draft report so the frontend can integrate
    before the Gemini API key is available.
    """
    behaviour_lines = "\n".join(
        f"- {b.behaviour_name}: {b.score}/5 ({b.notes or 'no notes provided'})"
        for b in data.behaviours
    )
    return f"""
[MOCK DRAFT REPORT - Gemini API not yet connected]

Patient: {data.patient_name}
Age: {data.age}
Assessment Date: {data.assessment_date}

Summary of Observations:
The child was observed across 10 communication behaviours during this session.

Behaviour Scores:
{behaviour_lines}

Strengths Noted:
(placeholder - will be generated by AI once connected)

Areas Needing Support:
(placeholder - will be generated by AI once connected)

Suggested Next Steps for the SLP to Consider:
(placeholder - will be generated by AI once connected)

NOTE: This is an automatically generated DRAFT and does not represent a diagnosis.
It must be reviewed and approved by a licensed Speech-Language Pathologist.
""".strip()


def call_gemini(prompt: str) -> str:
    """
    Placeholder for actual Gemini API call. Fill this in once you have
    a real GEMINI_API_KEY and the google-generativeai package installed.
    """
    import google.generativeai as genai

    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)
    return response.text


def generate_ai_report(data: AIReportRequest) -> AIReportResponse:
    if not GEMINI_API_KEY:
        draft_text = generate_mock_report(data)
    else:
        prompt = build_prompt(data)
        draft_text = call_gemini(prompt)

    return AIReportResponse(
        patient_name=data.patient_name,
        draft_report=draft_text,
    )