from pydantic import BaseModel, Field
from datetime import date
from typing import List


class BehaviourScore(BaseModel):
    behaviour_name: str
    score: int = Field(..., ge=0, le=5, description="Score from 0-5")
    notes: str = ""


class AIReportRequest(BaseModel):
    patient_name: str
    age: int
    assessment_date: date
    behaviours: List[BehaviourScore]

    class Config:
        json_schema_extra = {
            "example": {
                "patient_name": "John Doe",
                "age": 6,
                "assessment_date": "2026-07-31",
                "behaviours": [
                    {"behaviour_name": "Eye Contact", "score": 3, "notes": "Inconsistent during play"},
                    {"behaviour_name": "Joint Attention", "score": 2, "notes": "Needs prompting"},
                    {"behaviour_name": "Response to Name", "score": 4, "notes": "Responds most times"},
                    {"behaviour_name": "Gestures", "score": 3, "notes": "Uses pointing occasionally"},
                    {"behaviour_name": "Turn Taking", "score": 2, "notes": "Struggles in group settings"},
                    {"behaviour_name": "Initiation", "score": 2, "notes": "Rarely initiates interaction"},
                    {"behaviour_name": "Following Instructions", "score": 3, "notes": "Follows 1-step instructions"},
                    {"behaviour_name": "Requesting", "score": 3, "notes": "Requests using single words"},
                    {"behaviour_name": "Social Greeting", "score": 2, "notes": "Needs reminders to greet"},
                    {"behaviour_name": "Communication Intent", "score": 3, "notes": "Shows intent but limited means"},
                ],
            }
        }


class AIReportResponse(BaseModel):
    patient_name: str
    draft_report: str
    is_draft: bool = True
    disclaimer: str = (
        "This report was generated by AI and is a DRAFT only. "
        "It does not constitute a diagnosis. A licensed Speech-Language "
        "Pathologist must review, edit, and approve this report before use."
    )