from pydantic import BaseModel, Field
from datetime import date
from typing import List, Literal


class BehaviourScore(BaseModel):
    behaviour_name: str
    status: Literal["Present", "Absent"]
    therapist_notes: str = ""


class AIReportRequest(BaseModel):
    patient_name: str
    age: int
    assessment_date: date
    behaviours: List[BehaviourScore]

    class Config:
        json_schema_extra = {
            "example": {
                "patient_name": "John Doe",
                "age": 6,
                "assessment_date": "2026-07-31",
                "behaviours": [
                    {"behaviour_name": "Eye Contact", "status": "Absent", "therapist_notes": "Inconsistent during play"},
                    {"behaviour_name": "Joint Attention", "status": "Absent", "therapist_notes": "Needs prompting"},
                    {"behaviour_name": "Response to Name", "status": "Present", "therapist_notes": "Responds most times"},
                    {"behaviour_name": "Gestures", "status": "Present", "therapist_notes": "Uses pointing occasionally"},
                    {"behaviour_name": "Turn Taking", "status": "Absent", "therapist_notes": "Struggles in group settings"},
                    {"behaviour_name": "Initiation", "status": "Absent", "therapist_notes": "Rarely initiates interaction"},
                    {"behaviour_name": "Following Instructions", "status": "Present", "therapist_notes": "Follows 1-step instructions"},
                    {"behaviour_name": "Requesting", "status": "Present", "therapist_notes": "Requests using single words"},
                    {"behaviour_name": "Social Greeting", "status": "Absent", "therapist_notes": "Needs reminders to greet"},
                    {"behaviour_name": "Communication Intent", "status": "Present", "therapist_notes": "Shows intent but limited means"},
                ],
            }
        }


class AIReportResponse(BaseModel):
    patient_name: str
    clinical_impression: str
    recommendations: str
    parent_summary: str
    is_draft: bool = True
    disclaimer: str = (
        "This report was generated by AI and is a DRAFT only. "
        "It does not constitute a diagnosis. A licensed Speech-Language "
        "Pathologist must review, edit, and approve this report before use."
    )